/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

public class AppTest {
    public void testAppHasAGreeting() {
    	
    	System.out.printf("%s","hihi");
    	
     /*   App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());*/
    }
}
